// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Pineapple217/cvrs/pkg/ent/artist"
	"github.com/Pineapple217/cvrs/pkg/ent/image"
	"github.com/Pineapple217/cvrs/pkg/ent/predicate"
	"github.com/Pineapple217/cvrs/pkg/ent/release"
	"github.com/Pineapple217/cvrs/pkg/ent/releaseappearance"
	"github.com/Pineapple217/cvrs/pkg/ent/track"
	"github.com/Pineapple217/cvrs/pkg/ent/trackappearance"
	"github.com/Pineapple217/cvrs/pkg/pid"
)

// ArtistQuery is the builder for querying Artist entities.
type ArtistQuery struct {
	config
	ctx                   *QueryContext
	order                 []artist.OrderOption
	inters                []Interceptor
	predicates            []predicate.Artist
	withAppearingTracks   *TrackQuery
	withAppearingReleases *ReleaseQuery
	withImage             *ImageQuery
	withTrackAppearance   *TrackAppearanceQuery
	withReleaseAppearance *ReleaseAppearanceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ArtistQuery builder.
func (aq *ArtistQuery) Where(ps ...predicate.Artist) *ArtistQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit the number of records to be returned by this query.
func (aq *ArtistQuery) Limit(limit int) *ArtistQuery {
	aq.ctx.Limit = &limit
	return aq
}

// Offset to start from.
func (aq *ArtistQuery) Offset(offset int) *ArtistQuery {
	aq.ctx.Offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *ArtistQuery) Unique(unique bool) *ArtistQuery {
	aq.ctx.Unique = &unique
	return aq
}

// Order specifies how the records should be ordered.
func (aq *ArtistQuery) Order(o ...artist.OrderOption) *ArtistQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryAppearingTracks chains the current query on the "appearing_tracks" edge.
func (aq *ArtistQuery) QueryAppearingTracks() *TrackQuery {
	query := (&TrackClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(artist.Table, artist.FieldID, selector),
			sqlgraph.To(track.Table, track.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, artist.AppearingTracksTable, artist.AppearingTracksPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAppearingReleases chains the current query on the "appearing_releases" edge.
func (aq *ArtistQuery) QueryAppearingReleases() *ReleaseQuery {
	query := (&ReleaseClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(artist.Table, artist.FieldID, selector),
			sqlgraph.To(release.Table, release.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, artist.AppearingReleasesTable, artist.AppearingReleasesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryImage chains the current query on the "image" edge.
func (aq *ArtistQuery) QueryImage() *ImageQuery {
	query := (&ImageClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(artist.Table, artist.FieldID, selector),
			sqlgraph.To(image.Table, image.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, artist.ImageTable, artist.ImageColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTrackAppearance chains the current query on the "track_appearance" edge.
func (aq *ArtistQuery) QueryTrackAppearance() *TrackAppearanceQuery {
	query := (&TrackAppearanceClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(artist.Table, artist.FieldID, selector),
			sqlgraph.To(trackappearance.Table, trackappearance.ArtistColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, artist.TrackAppearanceTable, artist.TrackAppearanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReleaseAppearance chains the current query on the "release_appearance" edge.
func (aq *ArtistQuery) QueryReleaseAppearance() *ReleaseAppearanceQuery {
	query := (&ReleaseAppearanceClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(artist.Table, artist.FieldID, selector),
			sqlgraph.To(releaseappearance.Table, releaseappearance.ArtistColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, artist.ReleaseAppearanceTable, artist.ReleaseAppearanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Artist entity from the query.
// Returns a *NotFoundError when no Artist was found.
func (aq *ArtistQuery) First(ctx context.Context) (*Artist, error) {
	nodes, err := aq.Limit(1).All(setContextOp(ctx, aq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{artist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *ArtistQuery) FirstX(ctx context.Context) *Artist {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Artist ID from the query.
// Returns a *NotFoundError when no Artist ID was found.
func (aq *ArtistQuery) FirstID(ctx context.Context) (id pid.ID, err error) {
	var ids []pid.ID
	if ids, err = aq.Limit(1).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{artist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *ArtistQuery) FirstIDX(ctx context.Context) pid.ID {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Artist entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Artist entity is found.
// Returns a *NotFoundError when no Artist entities are found.
func (aq *ArtistQuery) Only(ctx context.Context) (*Artist, error) {
	nodes, err := aq.Limit(2).All(setContextOp(ctx, aq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{artist.Label}
	default:
		return nil, &NotSingularError{artist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *ArtistQuery) OnlyX(ctx context.Context) *Artist {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Artist ID in the query.
// Returns a *NotSingularError when more than one Artist ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *ArtistQuery) OnlyID(ctx context.Context) (id pid.ID, err error) {
	var ids []pid.ID
	if ids, err = aq.Limit(2).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{artist.Label}
	default:
		err = &NotSingularError{artist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *ArtistQuery) OnlyIDX(ctx context.Context) pid.ID {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Artists.
func (aq *ArtistQuery) All(ctx context.Context) ([]*Artist, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryAll)
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Artist, *ArtistQuery]()
	return withInterceptors[[]*Artist](ctx, aq, qr, aq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aq *ArtistQuery) AllX(ctx context.Context) []*Artist {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Artist IDs.
func (aq *ArtistQuery) IDs(ctx context.Context) (ids []pid.ID, err error) {
	if aq.ctx.Unique == nil && aq.path != nil {
		aq.Unique(true)
	}
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryIDs)
	if err = aq.Select(artist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *ArtistQuery) IDsX(ctx context.Context) []pid.ID {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *ArtistQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryCount)
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aq, querierCount[*ArtistQuery](), aq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aq *ArtistQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *ArtistQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryExist)
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *ArtistQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ArtistQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *ArtistQuery) Clone() *ArtistQuery {
	if aq == nil {
		return nil
	}
	return &ArtistQuery{
		config:                aq.config,
		ctx:                   aq.ctx.Clone(),
		order:                 append([]artist.OrderOption{}, aq.order...),
		inters:                append([]Interceptor{}, aq.inters...),
		predicates:            append([]predicate.Artist{}, aq.predicates...),
		withAppearingTracks:   aq.withAppearingTracks.Clone(),
		withAppearingReleases: aq.withAppearingReleases.Clone(),
		withImage:             aq.withImage.Clone(),
		withTrackAppearance:   aq.withTrackAppearance.Clone(),
		withReleaseAppearance: aq.withReleaseAppearance.Clone(),
		// clone intermediate query.
		sql:  aq.sql.Clone(),
		path: aq.path,
	}
}

// WithAppearingTracks tells the query-builder to eager-load the nodes that are connected to
// the "appearing_tracks" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *ArtistQuery) WithAppearingTracks(opts ...func(*TrackQuery)) *ArtistQuery {
	query := (&TrackClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withAppearingTracks = query
	return aq
}

// WithAppearingReleases tells the query-builder to eager-load the nodes that are connected to
// the "appearing_releases" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *ArtistQuery) WithAppearingReleases(opts ...func(*ReleaseQuery)) *ArtistQuery {
	query := (&ReleaseClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withAppearingReleases = query
	return aq
}

// WithImage tells the query-builder to eager-load the nodes that are connected to
// the "image" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *ArtistQuery) WithImage(opts ...func(*ImageQuery)) *ArtistQuery {
	query := (&ImageClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withImage = query
	return aq
}

// WithTrackAppearance tells the query-builder to eager-load the nodes that are connected to
// the "track_appearance" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *ArtistQuery) WithTrackAppearance(opts ...func(*TrackAppearanceQuery)) *ArtistQuery {
	query := (&TrackAppearanceClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withTrackAppearance = query
	return aq
}

// WithReleaseAppearance tells the query-builder to eager-load the nodes that are connected to
// the "release_appearance" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *ArtistQuery) WithReleaseAppearance(opts ...func(*ReleaseAppearanceQuery)) *ArtistQuery {
	query := (&ReleaseAppearanceClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withReleaseAppearance = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Artist.Query().
//		GroupBy(artist.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *ArtistQuery) GroupBy(field string, fields ...string) *ArtistGroupBy {
	aq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ArtistGroupBy{build: aq}
	grbuild.flds = &aq.ctx.Fields
	grbuild.label = artist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Artist.Query().
//		Select(artist.FieldName).
//		Scan(ctx, &v)
func (aq *ArtistQuery) Select(fields ...string) *ArtistSelect {
	aq.ctx.Fields = append(aq.ctx.Fields, fields...)
	sbuild := &ArtistSelect{ArtistQuery: aq}
	sbuild.label = artist.Label
	sbuild.flds, sbuild.scan = &aq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ArtistSelect configured with the given aggregations.
func (aq *ArtistQuery) Aggregate(fns ...AggregateFunc) *ArtistSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *ArtistQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aq); err != nil {
				return err
			}
		}
	}
	for _, f := range aq.ctx.Fields {
		if !artist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *ArtistQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Artist, error) {
	var (
		nodes       = []*Artist{}
		_spec       = aq.querySpec()
		loadedTypes = [5]bool{
			aq.withAppearingTracks != nil,
			aq.withAppearingReleases != nil,
			aq.withImage != nil,
			aq.withTrackAppearance != nil,
			aq.withReleaseAppearance != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Artist).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Artist{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withAppearingTracks; query != nil {
		if err := aq.loadAppearingTracks(ctx, query, nodes,
			func(n *Artist) { n.Edges.AppearingTracks = []*Track{} },
			func(n *Artist, e *Track) { n.Edges.AppearingTracks = append(n.Edges.AppearingTracks, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withAppearingReleases; query != nil {
		if err := aq.loadAppearingReleases(ctx, query, nodes,
			func(n *Artist) { n.Edges.AppearingReleases = []*Release{} },
			func(n *Artist, e *Release) { n.Edges.AppearingReleases = append(n.Edges.AppearingReleases, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withImage; query != nil {
		if err := aq.loadImage(ctx, query, nodes, nil,
			func(n *Artist, e *Image) { n.Edges.Image = e }); err != nil {
			return nil, err
		}
	}
	if query := aq.withTrackAppearance; query != nil {
		if err := aq.loadTrackAppearance(ctx, query, nodes,
			func(n *Artist) { n.Edges.TrackAppearance = []*TrackAppearance{} },
			func(n *Artist, e *TrackAppearance) { n.Edges.TrackAppearance = append(n.Edges.TrackAppearance, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withReleaseAppearance; query != nil {
		if err := aq.loadReleaseAppearance(ctx, query, nodes,
			func(n *Artist) { n.Edges.ReleaseAppearance = []*ReleaseAppearance{} },
			func(n *Artist, e *ReleaseAppearance) {
				n.Edges.ReleaseAppearance = append(n.Edges.ReleaseAppearance, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *ArtistQuery) loadAppearingTracks(ctx context.Context, query *TrackQuery, nodes []*Artist, init func(*Artist), assign func(*Artist, *Track)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[pid.ID]*Artist)
	nids := make(map[pid.ID]map[*Artist]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(artist.AppearingTracksTable)
		s.Join(joinT).On(s.C(track.FieldID), joinT.C(artist.AppearingTracksPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(artist.AppearingTracksPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(artist.AppearingTracksPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := pid.ID(values[0].(*sql.NullInt64).Int64)
				inValue := pid.ID(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Artist]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Track](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "appearing_tracks" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (aq *ArtistQuery) loadAppearingReleases(ctx context.Context, query *ReleaseQuery, nodes []*Artist, init func(*Artist), assign func(*Artist, *Release)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[pid.ID]*Artist)
	nids := make(map[pid.ID]map[*Artist]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(artist.AppearingReleasesTable)
		s.Join(joinT).On(s.C(release.FieldID), joinT.C(artist.AppearingReleasesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(artist.AppearingReleasesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(artist.AppearingReleasesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := pid.ID(values[0].(*sql.NullInt64).Int64)
				inValue := pid.ID(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Artist]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Release](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "appearing_releases" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (aq *ArtistQuery) loadImage(ctx context.Context, query *ImageQuery, nodes []*Artist, init func(*Artist), assign func(*Artist, *Image)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[pid.ID]*Artist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Image(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(artist.ImageColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.artist_image
		if fk == nil {
			return fmt.Errorf(`foreign-key "artist_image" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "artist_image" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *ArtistQuery) loadTrackAppearance(ctx context.Context, query *TrackAppearanceQuery, nodes []*Artist, init func(*Artist), assign func(*Artist, *TrackAppearance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[pid.ID]*Artist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(trackappearance.FieldArtistID)
	}
	query.Where(predicate.TrackAppearance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(artist.TrackAppearanceColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ArtistID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "artist_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}
func (aq *ArtistQuery) loadReleaseAppearance(ctx context.Context, query *ReleaseAppearanceQuery, nodes []*Artist, init func(*Artist), assign func(*Artist, *ReleaseAppearance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[pid.ID]*Artist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(releaseappearance.FieldArtistID)
	}
	query.Where(predicate.ReleaseAppearance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(artist.ReleaseAppearanceColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ArtistID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "artist_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (aq *ArtistQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	_spec.Node.Columns = aq.ctx.Fields
	if len(aq.ctx.Fields) > 0 {
		_spec.Unique = aq.ctx.Unique != nil && *aq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *ArtistQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(artist.Table, artist.Columns, sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt64))
	_spec.From = aq.sql
	if unique := aq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aq.path != nil {
		_spec.Unique = true
	}
	if fields := aq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, artist.FieldID)
		for i := range fields {
			if fields[i] != artist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *ArtistQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(artist.Table)
	columns := aq.ctx.Fields
	if len(columns) == 0 {
		columns = artist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.ctx.Unique != nil && *aq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ArtistGroupBy is the group-by builder for Artist entities.
type ArtistGroupBy struct {
	selector
	build *ArtistQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *ArtistGroupBy) Aggregate(fns ...AggregateFunc) *ArtistGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the selector query and scans the result into the given value.
func (agb *ArtistGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agb.build.ctx, ent.OpQueryGroupBy)
	if err := agb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ArtistQuery, *ArtistGroupBy](ctx, agb.build, agb, agb.build.inters, v)
}

func (agb *ArtistGroupBy) sqlScan(ctx context.Context, root *ArtistQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agb.flds)+len(agb.fns))
		for _, f := range *agb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ArtistSelect is the builder for selecting fields of Artist entities.
type ArtistSelect struct {
	*ArtistQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *ArtistSelect) Aggregate(fns ...AggregateFunc) *ArtistSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *ArtistSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, as.ctx, ent.OpQuerySelect)
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ArtistQuery, *ArtistSelect](ctx, as.ArtistQuery, as, as.inters, v)
}

func (as *ArtistSelect) sqlScan(ctx context.Context, root *ArtistQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
