// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Pineapple217/cvrs/pkg/ent/artist"
	"github.com/Pineapple217/cvrs/pkg/ent/image"
	"github.com/Pineapple217/cvrs/pkg/pid"
)

// Artist is the model entity for the Artist schema.
type Artist struct {
	config `json:"-"`
	// ID of the ent.
	ID pid.ID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitzero"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitzero"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitzero"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArtistQuery when eager-loading is set.
	Edges        ArtistEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArtistEdges holds the relations/edges for other nodes in the graph.
type ArtistEdges struct {
	// AppearingTracks holds the value of the appearing_tracks edge.
	AppearingTracks []*Track `json:"appearing_tracks,omitempty"`
	// AppearingReleases holds the value of the appearing_releases edge.
	AppearingReleases []*Release `json:"appearing_releases,omitempty"`
	// Image holds the value of the image edge.
	Image *Image `json:"image,omitempty"`
	// TrackAppearance holds the value of the track_appearance edge.
	TrackAppearance []*TrackAppearance `json:"track_appearance,omitempty"`
	// ReleaseAppearance holds the value of the release_appearance edge.
	ReleaseAppearance []*ReleaseAppearance `json:"release_appearance,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AppearingTracksOrErr returns the AppearingTracks value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) AppearingTracksOrErr() ([]*Track, error) {
	if e.loadedTypes[0] {
		return e.AppearingTracks, nil
	}
	return nil, &NotLoadedError{edge: "appearing_tracks"}
}

// AppearingReleasesOrErr returns the AppearingReleases value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) AppearingReleasesOrErr() ([]*Release, error) {
	if e.loadedTypes[1] {
		return e.AppearingReleases, nil
	}
	return nil, &NotLoadedError{edge: "appearing_releases"}
}

// ImageOrErr returns the Image value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArtistEdges) ImageOrErr() (*Image, error) {
	if e.Image != nil {
		return e.Image, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: image.Label}
	}
	return nil, &NotLoadedError{edge: "image"}
}

// TrackAppearanceOrErr returns the TrackAppearance value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) TrackAppearanceOrErr() ([]*TrackAppearance, error) {
	if e.loadedTypes[3] {
		return e.TrackAppearance, nil
	}
	return nil, &NotLoadedError{edge: "track_appearance"}
}

// ReleaseAppearanceOrErr returns the ReleaseAppearance value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) ReleaseAppearanceOrErr() ([]*ReleaseAppearance, error) {
	if e.loadedTypes[4] {
		return e.ReleaseAppearance, nil
	}
	return nil, &NotLoadedError{edge: "release_appearance"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Artist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case artist.FieldID:
			values[i] = new(sql.NullInt64)
		case artist.FieldName:
			values[i] = new(sql.NullString)
		case artist.FieldCreatedAt, artist.FieldUpdatedAt, artist.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Artist fields.
func (a *Artist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case artist.FieldID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				a.ID = pid.ID(value.Int64)
			}
		case artist.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case artist.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		case artist.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				a.UpdatedAt = value.Time
			}
		case artist.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				a.DeletedAt = new(time.Time)
				*a.DeletedAt = value.Time
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Artist.
// This includes values selected through modifiers, order, etc.
func (a *Artist) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QueryAppearingTracks queries the "appearing_tracks" edge of the Artist entity.
func (a *Artist) QueryAppearingTracks() *TrackQuery {
	return NewArtistClient(a.config).QueryAppearingTracks(a)
}

// QueryAppearingReleases queries the "appearing_releases" edge of the Artist entity.
func (a *Artist) QueryAppearingReleases() *ReleaseQuery {
	return NewArtistClient(a.config).QueryAppearingReleases(a)
}

// QueryImage queries the "image" edge of the Artist entity.
func (a *Artist) QueryImage() *ImageQuery {
	return NewArtistClient(a.config).QueryImage(a)
}

// QueryTrackAppearance queries the "track_appearance" edge of the Artist entity.
func (a *Artist) QueryTrackAppearance() *TrackAppearanceQuery {
	return NewArtistClient(a.config).QueryTrackAppearance(a)
}

// QueryReleaseAppearance queries the "release_appearance" edge of the Artist entity.
func (a *Artist) QueryReleaseAppearance() *ReleaseAppearanceQuery {
	return NewArtistClient(a.config).QueryReleaseAppearance(a)
}

// Update returns a builder for updating this Artist.
// Note that you need to call Artist.Unwrap() before calling this method if this Artist
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Artist) Update() *ArtistUpdateOne {
	return NewArtistClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Artist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Artist) Unwrap() *Artist {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Artist is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Artist) String() string {
	var builder strings.Builder
	builder.WriteString("Artist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(a.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := a.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Artists is a parsable slice of Artist.
type Artists []*Artist
