// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Pineapple217/cvrs/pkg/ent/imagedata"
	"github.com/Pineapple217/cvrs/pkg/ent/predicate"
)

// ImageDataDelete is the builder for deleting a ImageData entity.
type ImageDataDelete struct {
	config
	hooks    []Hook
	mutation *ImageDataMutation
}

// Where appends a list predicates to the ImageDataDelete builder.
func (idd *ImageDataDelete) Where(ps ...predicate.ImageData) *ImageDataDelete {
	idd.mutation.Where(ps...)
	return idd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (idd *ImageDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, idd.sqlExec, idd.mutation, idd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (idd *ImageDataDelete) ExecX(ctx context.Context) int {
	n, err := idd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (idd *ImageDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(imagedata.Table, sqlgraph.NewFieldSpec(imagedata.FieldID, field.TypeInt))
	if ps := idd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, idd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	idd.mutation.done = true
	return affected, err
}

// ImageDataDeleteOne is the builder for deleting a single ImageData entity.
type ImageDataDeleteOne struct {
	idd *ImageDataDelete
}

// Where appends a list predicates to the ImageDataDelete builder.
func (iddo *ImageDataDeleteOne) Where(ps ...predicate.ImageData) *ImageDataDeleteOne {
	iddo.idd.mutation.Where(ps...)
	return iddo
}

// Exec executes the deletion query.
func (iddo *ImageDataDeleteOne) Exec(ctx context.Context) error {
	n, err := iddo.idd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{imagedata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iddo *ImageDataDeleteOne) ExecX(ctx context.Context) {
	if err := iddo.Exec(ctx); err != nil {
		panic(err)
	}
}
