// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Pineapple217/cvrs/pkg/ent/image"
	"github.com/Pineapple217/cvrs/pkg/ent/predicate"
	"github.com/Pineapple217/cvrs/pkg/ent/processedimage"
	"github.com/Pineapple217/cvrs/pkg/pid"
)

// ProcessedImageQuery is the builder for querying ProcessedImage entities.
type ProcessedImageQuery struct {
	config
	ctx        *QueryContext
	order      []processedimage.OrderOption
	inters     []Interceptor
	predicates []predicate.ProcessedImage
	withSource *ImageQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProcessedImageQuery builder.
func (piq *ProcessedImageQuery) Where(ps ...predicate.ProcessedImage) *ProcessedImageQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *ProcessedImageQuery) Limit(limit int) *ProcessedImageQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *ProcessedImageQuery) Offset(offset int) *ProcessedImageQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *ProcessedImageQuery) Unique(unique bool) *ProcessedImageQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *ProcessedImageQuery) Order(o ...processedimage.OrderOption) *ProcessedImageQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QuerySource chains the current query on the "source" edge.
func (piq *ProcessedImageQuery) QuerySource() *ImageQuery {
	query := (&ImageClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(processedimage.Table, processedimage.FieldID, selector),
			sqlgraph.To(image.Table, image.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, processedimage.SourceTable, processedimage.SourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProcessedImage entity from the query.
// Returns a *NotFoundError when no ProcessedImage was found.
func (piq *ProcessedImageQuery) First(ctx context.Context) (*ProcessedImage, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{processedimage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *ProcessedImageQuery) FirstX(ctx context.Context) *ProcessedImage {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProcessedImage ID from the query.
// Returns a *NotFoundError when no ProcessedImage ID was found.
func (piq *ProcessedImageQuery) FirstID(ctx context.Context) (id pid.ID, err error) {
	var ids []pid.ID
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{processedimage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *ProcessedImageQuery) FirstIDX(ctx context.Context) pid.ID {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProcessedImage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProcessedImage entity is found.
// Returns a *NotFoundError when no ProcessedImage entities are found.
func (piq *ProcessedImageQuery) Only(ctx context.Context) (*ProcessedImage, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{processedimage.Label}
	default:
		return nil, &NotSingularError{processedimage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *ProcessedImageQuery) OnlyX(ctx context.Context) *ProcessedImage {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProcessedImage ID in the query.
// Returns a *NotSingularError when more than one ProcessedImage ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *ProcessedImageQuery) OnlyID(ctx context.Context) (id pid.ID, err error) {
	var ids []pid.ID
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{processedimage.Label}
	default:
		err = &NotSingularError{processedimage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *ProcessedImageQuery) OnlyIDX(ctx context.Context) pid.ID {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProcessedImages.
func (piq *ProcessedImageQuery) All(ctx context.Context) ([]*ProcessedImage, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryAll)
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProcessedImage, *ProcessedImageQuery]()
	return withInterceptors[[]*ProcessedImage](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *ProcessedImageQuery) AllX(ctx context.Context) []*ProcessedImage {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProcessedImage IDs.
func (piq *ProcessedImageQuery) IDs(ctx context.Context) (ids []pid.ID, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryIDs)
	if err = piq.Select(processedimage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *ProcessedImageQuery) IDsX(ctx context.Context) []pid.ID {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *ProcessedImageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryCount)
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*ProcessedImageQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *ProcessedImageQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *ProcessedImageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryExist)
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *ProcessedImageQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProcessedImageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *ProcessedImageQuery) Clone() *ProcessedImageQuery {
	if piq == nil {
		return nil
	}
	return &ProcessedImageQuery{
		config:     piq.config,
		ctx:        piq.ctx.Clone(),
		order:      append([]processedimage.OrderOption{}, piq.order...),
		inters:     append([]Interceptor{}, piq.inters...),
		predicates: append([]predicate.ProcessedImage{}, piq.predicates...),
		withSource: piq.withSource.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithSource tells the query-builder to eager-load the nodes that are connected to
// the "source" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *ProcessedImageQuery) WithSource(opts ...func(*ImageQuery)) *ProcessedImageQuery {
	query := (&ImageClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withSource = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type processedimage.Type `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProcessedImage.Query().
//		GroupBy(processedimage.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *ProcessedImageQuery) GroupBy(field string, fields ...string) *ProcessedImageGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProcessedImageGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = processedimage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type processedimage.Type `json:"type,omitempty"`
//	}
//
//	client.ProcessedImage.Query().
//		Select(processedimage.FieldType).
//		Scan(ctx, &v)
func (piq *ProcessedImageQuery) Select(fields ...string) *ProcessedImageSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &ProcessedImageSelect{ProcessedImageQuery: piq}
	sbuild.label = processedimage.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProcessedImageSelect configured with the given aggregations.
func (piq *ProcessedImageQuery) Aggregate(fns ...AggregateFunc) *ProcessedImageSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *ProcessedImageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !processedimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *ProcessedImageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProcessedImage, error) {
	var (
		nodes       = []*ProcessedImage{}
		withFKs     = piq.withFKs
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withSource != nil,
		}
	)
	if piq.withSource != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, processedimage.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProcessedImage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProcessedImage{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withSource; query != nil {
		if err := piq.loadSource(ctx, query, nodes, nil,
			func(n *ProcessedImage, e *Image) { n.Edges.Source = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *ProcessedImageQuery) loadSource(ctx context.Context, query *ImageQuery, nodes []*ProcessedImage, init func(*ProcessedImage), assign func(*ProcessedImage, *Image)) error {
	ids := make([]pid.ID, 0, len(nodes))
	nodeids := make(map[pid.ID][]*ProcessedImage)
	for i := range nodes {
		if nodes[i].image_proccesed_image == nil {
			continue
		}
		fk := *nodes[i].image_proccesed_image
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(image.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "image_proccesed_image" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piq *ProcessedImageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *ProcessedImageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(processedimage.Table, processedimage.Columns, sqlgraph.NewFieldSpec(processedimage.FieldID, field.TypeInt64))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processedimage.FieldID)
		for i := range fields {
			if fields[i] != processedimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *ProcessedImageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(processedimage.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = processedimage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProcessedImageGroupBy is the group-by builder for ProcessedImage entities.
type ProcessedImageGroupBy struct {
	selector
	build *ProcessedImageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *ProcessedImageGroupBy) Aggregate(fns ...AggregateFunc) *ProcessedImageGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *ProcessedImageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, ent.OpQueryGroupBy)
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcessedImageQuery, *ProcessedImageGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *ProcessedImageGroupBy) sqlScan(ctx context.Context, root *ProcessedImageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProcessedImageSelect is the builder for selecting fields of ProcessedImage entities.
type ProcessedImageSelect struct {
	*ProcessedImageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *ProcessedImageSelect) Aggregate(fns ...AggregateFunc) *ProcessedImageSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *ProcessedImageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, ent.OpQuerySelect)
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcessedImageQuery, *ProcessedImageSelect](ctx, pis.ProcessedImageQuery, pis, pis.inters, v)
}

func (pis *ProcessedImageSelect) sqlScan(ctx context.Context, root *ProcessedImageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
