// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Pineapple217/cvrs/pkg/ent/artist"
	"github.com/Pineapple217/cvrs/pkg/ent/predicate"
	"github.com/Pineapple217/cvrs/pkg/ent/release"
	"github.com/Pineapple217/cvrs/pkg/ent/releaseappearance"
	"github.com/Pineapple217/cvrs/pkg/pid"
)

// ReleaseAppearanceQuery is the builder for querying ReleaseAppearance entities.
type ReleaseAppearanceQuery struct {
	config
	ctx         *QueryContext
	order       []releaseappearance.OrderOption
	inters      []Interceptor
	predicates  []predicate.ReleaseAppearance
	withArtist  *ArtistQuery
	withRelease *ReleaseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReleaseAppearanceQuery builder.
func (raq *ReleaseAppearanceQuery) Where(ps ...predicate.ReleaseAppearance) *ReleaseAppearanceQuery {
	raq.predicates = append(raq.predicates, ps...)
	return raq
}

// Limit the number of records to be returned by this query.
func (raq *ReleaseAppearanceQuery) Limit(limit int) *ReleaseAppearanceQuery {
	raq.ctx.Limit = &limit
	return raq
}

// Offset to start from.
func (raq *ReleaseAppearanceQuery) Offset(offset int) *ReleaseAppearanceQuery {
	raq.ctx.Offset = &offset
	return raq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (raq *ReleaseAppearanceQuery) Unique(unique bool) *ReleaseAppearanceQuery {
	raq.ctx.Unique = &unique
	return raq
}

// Order specifies how the records should be ordered.
func (raq *ReleaseAppearanceQuery) Order(o ...releaseappearance.OrderOption) *ReleaseAppearanceQuery {
	raq.order = append(raq.order, o...)
	return raq
}

// QueryArtist chains the current query on the "artist" edge.
func (raq *ReleaseAppearanceQuery) QueryArtist() *ArtistQuery {
	query := (&ArtistClient{config: raq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := raq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := raq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(releaseappearance.Table, releaseappearance.ArtistColumn, selector),
			sqlgraph.To(artist.Table, artist.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, releaseappearance.ArtistTable, releaseappearance.ArtistColumn),
		)
		fromU = sqlgraph.SetNeighbors(raq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelease chains the current query on the "release" edge.
func (raq *ReleaseAppearanceQuery) QueryRelease() *ReleaseQuery {
	query := (&ReleaseClient{config: raq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := raq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := raq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(releaseappearance.Table, releaseappearance.ReleaseColumn, selector),
			sqlgraph.To(release.Table, release.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, releaseappearance.ReleaseTable, releaseappearance.ReleaseColumn),
		)
		fromU = sqlgraph.SetNeighbors(raq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReleaseAppearance entity from the query.
// Returns a *NotFoundError when no ReleaseAppearance was found.
func (raq *ReleaseAppearanceQuery) First(ctx context.Context) (*ReleaseAppearance, error) {
	nodes, err := raq.Limit(1).All(setContextOp(ctx, raq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{releaseappearance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (raq *ReleaseAppearanceQuery) FirstX(ctx context.Context) *ReleaseAppearance {
	node, err := raq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single ReleaseAppearance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReleaseAppearance entity is found.
// Returns a *NotFoundError when no ReleaseAppearance entities are found.
func (raq *ReleaseAppearanceQuery) Only(ctx context.Context) (*ReleaseAppearance, error) {
	nodes, err := raq.Limit(2).All(setContextOp(ctx, raq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{releaseappearance.Label}
	default:
		return nil, &NotSingularError{releaseappearance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (raq *ReleaseAppearanceQuery) OnlyX(ctx context.Context) *ReleaseAppearance {
	node, err := raq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of ReleaseAppearances.
func (raq *ReleaseAppearanceQuery) All(ctx context.Context) ([]*ReleaseAppearance, error) {
	ctx = setContextOp(ctx, raq.ctx, ent.OpQueryAll)
	if err := raq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReleaseAppearance, *ReleaseAppearanceQuery]()
	return withInterceptors[[]*ReleaseAppearance](ctx, raq, qr, raq.inters)
}

// AllX is like All, but panics if an error occurs.
func (raq *ReleaseAppearanceQuery) AllX(ctx context.Context) []*ReleaseAppearance {
	nodes, err := raq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (raq *ReleaseAppearanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, raq.ctx, ent.OpQueryCount)
	if err := raq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, raq, querierCount[*ReleaseAppearanceQuery](), raq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (raq *ReleaseAppearanceQuery) CountX(ctx context.Context) int {
	count, err := raq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (raq *ReleaseAppearanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, raq.ctx, ent.OpQueryExist)
	switch _, err := raq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (raq *ReleaseAppearanceQuery) ExistX(ctx context.Context) bool {
	exist, err := raq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReleaseAppearanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (raq *ReleaseAppearanceQuery) Clone() *ReleaseAppearanceQuery {
	if raq == nil {
		return nil
	}
	return &ReleaseAppearanceQuery{
		config:      raq.config,
		ctx:         raq.ctx.Clone(),
		order:       append([]releaseappearance.OrderOption{}, raq.order...),
		inters:      append([]Interceptor{}, raq.inters...),
		predicates:  append([]predicate.ReleaseAppearance{}, raq.predicates...),
		withArtist:  raq.withArtist.Clone(),
		withRelease: raq.withRelease.Clone(),
		// clone intermediate query.
		sql:  raq.sql.Clone(),
		path: raq.path,
	}
}

// WithArtist tells the query-builder to eager-load the nodes that are connected to
// the "artist" edge. The optional arguments are used to configure the query builder of the edge.
func (raq *ReleaseAppearanceQuery) WithArtist(opts ...func(*ArtistQuery)) *ReleaseAppearanceQuery {
	query := (&ArtistClient{config: raq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	raq.withArtist = query
	return raq
}

// WithRelease tells the query-builder to eager-load the nodes that are connected to
// the "release" edge. The optional arguments are used to configure the query builder of the edge.
func (raq *ReleaseAppearanceQuery) WithRelease(opts ...func(*ReleaseQuery)) *ReleaseAppearanceQuery {
	query := (&ReleaseClient{config: raq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	raq.withRelease = query
	return raq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ReleaseID pid.ID `json:"release_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReleaseAppearance.Query().
//		GroupBy(releaseappearance.FieldReleaseID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (raq *ReleaseAppearanceQuery) GroupBy(field string, fields ...string) *ReleaseAppearanceGroupBy {
	raq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReleaseAppearanceGroupBy{build: raq}
	grbuild.flds = &raq.ctx.Fields
	grbuild.label = releaseappearance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ReleaseID pid.ID `json:"release_id,omitempty"`
//	}
//
//	client.ReleaseAppearance.Query().
//		Select(releaseappearance.FieldReleaseID).
//		Scan(ctx, &v)
func (raq *ReleaseAppearanceQuery) Select(fields ...string) *ReleaseAppearanceSelect {
	raq.ctx.Fields = append(raq.ctx.Fields, fields...)
	sbuild := &ReleaseAppearanceSelect{ReleaseAppearanceQuery: raq}
	sbuild.label = releaseappearance.Label
	sbuild.flds, sbuild.scan = &raq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReleaseAppearanceSelect configured with the given aggregations.
func (raq *ReleaseAppearanceQuery) Aggregate(fns ...AggregateFunc) *ReleaseAppearanceSelect {
	return raq.Select().Aggregate(fns...)
}

func (raq *ReleaseAppearanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range raq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, raq); err != nil {
				return err
			}
		}
	}
	for _, f := range raq.ctx.Fields {
		if !releaseappearance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if raq.path != nil {
		prev, err := raq.path(ctx)
		if err != nil {
			return err
		}
		raq.sql = prev
	}
	return nil
}

func (raq *ReleaseAppearanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReleaseAppearance, error) {
	var (
		nodes       = []*ReleaseAppearance{}
		_spec       = raq.querySpec()
		loadedTypes = [2]bool{
			raq.withArtist != nil,
			raq.withRelease != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReleaseAppearance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReleaseAppearance{config: raq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, raq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := raq.withArtist; query != nil {
		if err := raq.loadArtist(ctx, query, nodes, nil,
			func(n *ReleaseAppearance, e *Artist) { n.Edges.Artist = e }); err != nil {
			return nil, err
		}
	}
	if query := raq.withRelease; query != nil {
		if err := raq.loadRelease(ctx, query, nodes, nil,
			func(n *ReleaseAppearance, e *Release) { n.Edges.Release = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (raq *ReleaseAppearanceQuery) loadArtist(ctx context.Context, query *ArtistQuery, nodes []*ReleaseAppearance, init func(*ReleaseAppearance), assign func(*ReleaseAppearance, *Artist)) error {
	ids := make([]pid.ID, 0, len(nodes))
	nodeids := make(map[pid.ID][]*ReleaseAppearance)
	for i := range nodes {
		fk := nodes[i].ArtistID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(artist.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "artist_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (raq *ReleaseAppearanceQuery) loadRelease(ctx context.Context, query *ReleaseQuery, nodes []*ReleaseAppearance, init func(*ReleaseAppearance), assign func(*ReleaseAppearance, *Release)) error {
	ids := make([]pid.ID, 0, len(nodes))
	nodeids := make(map[pid.ID][]*ReleaseAppearance)
	for i := range nodes {
		fk := nodes[i].ReleaseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(release.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "release_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (raq *ReleaseAppearanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := raq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, raq.driver, _spec)
}

func (raq *ReleaseAppearanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(releaseappearance.Table, releaseappearance.Columns, nil)
	_spec.From = raq.sql
	if unique := raq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if raq.path != nil {
		_spec.Unique = true
	}
	if fields := raq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if raq.withArtist != nil {
			_spec.Node.AddColumnOnce(releaseappearance.FieldArtistID)
		}
		if raq.withRelease != nil {
			_spec.Node.AddColumnOnce(releaseappearance.FieldReleaseID)
		}
	}
	if ps := raq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := raq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := raq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := raq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (raq *ReleaseAppearanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(raq.driver.Dialect())
	t1 := builder.Table(releaseappearance.Table)
	columns := raq.ctx.Fields
	if len(columns) == 0 {
		columns = releaseappearance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if raq.sql != nil {
		selector = raq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if raq.ctx.Unique != nil && *raq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range raq.predicates {
		p(selector)
	}
	for _, p := range raq.order {
		p(selector)
	}
	if offset := raq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := raq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReleaseAppearanceGroupBy is the group-by builder for ReleaseAppearance entities.
type ReleaseAppearanceGroupBy struct {
	selector
	build *ReleaseAppearanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ragb *ReleaseAppearanceGroupBy) Aggregate(fns ...AggregateFunc) *ReleaseAppearanceGroupBy {
	ragb.fns = append(ragb.fns, fns...)
	return ragb
}

// Scan applies the selector query and scans the result into the given value.
func (ragb *ReleaseAppearanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ragb.build.ctx, ent.OpQueryGroupBy)
	if err := ragb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReleaseAppearanceQuery, *ReleaseAppearanceGroupBy](ctx, ragb.build, ragb, ragb.build.inters, v)
}

func (ragb *ReleaseAppearanceGroupBy) sqlScan(ctx context.Context, root *ReleaseAppearanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ragb.fns))
	for _, fn := range ragb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ragb.flds)+len(ragb.fns))
		for _, f := range *ragb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ragb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ragb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReleaseAppearanceSelect is the builder for selecting fields of ReleaseAppearance entities.
type ReleaseAppearanceSelect struct {
	*ReleaseAppearanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ras *ReleaseAppearanceSelect) Aggregate(fns ...AggregateFunc) *ReleaseAppearanceSelect {
	ras.fns = append(ras.fns, fns...)
	return ras
}

// Scan applies the selector query and scans the result into the given value.
func (ras *ReleaseAppearanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ras.ctx, ent.OpQuerySelect)
	if err := ras.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReleaseAppearanceQuery, *ReleaseAppearanceSelect](ctx, ras.ReleaseAppearanceQuery, ras, ras.inters, v)
}

func (ras *ReleaseAppearanceSelect) sqlScan(ctx context.Context, root *ReleaseAppearanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ras.fns))
	for _, fn := range ras.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ras.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ras.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
