// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Pineapple217/cvrs/pkg/ent/predicate"
	"github.com/Pineapple217/cvrs/pkg/ent/trackappearance"
)

// TrackAppearanceDelete is the builder for deleting a TrackAppearance entity.
type TrackAppearanceDelete struct {
	config
	hooks    []Hook
	mutation *TrackAppearanceMutation
}

// Where appends a list predicates to the TrackAppearanceDelete builder.
func (tad *TrackAppearanceDelete) Where(ps ...predicate.TrackAppearance) *TrackAppearanceDelete {
	tad.mutation.Where(ps...)
	return tad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tad *TrackAppearanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tad.sqlExec, tad.mutation, tad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tad *TrackAppearanceDelete) ExecX(ctx context.Context) int {
	n, err := tad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tad *TrackAppearanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(trackappearance.Table, nil)
	if ps := tad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tad.mutation.done = true
	return affected, err
}

// TrackAppearanceDeleteOne is the builder for deleting a single TrackAppearance entity.
type TrackAppearanceDeleteOne struct {
	tad *TrackAppearanceDelete
}

// Where appends a list predicates to the TrackAppearanceDelete builder.
func (tado *TrackAppearanceDeleteOne) Where(ps ...predicate.TrackAppearance) *TrackAppearanceDeleteOne {
	tado.tad.mutation.Where(ps...)
	return tado
}

// Exec executes the deletion query.
func (tado *TrackAppearanceDeleteOne) Exec(ctx context.Context) error {
	n, err := tado.tad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trackappearance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tado *TrackAppearanceDeleteOne) ExecX(ctx context.Context) {
	if err := tado.Exec(ctx); err != nil {
		panic(err)
	}
}
