// Code generated by ent, DO NOT EDIT.

package releaseappearance

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Pineapple217/cvrs/pkg/pid"
)

const (
	// Label holds the string label denoting the releaseappearance type in the database.
	Label = "release_appearance"
	// FieldReleaseID holds the string denoting the release_id field in the database.
	FieldReleaseID = "release_id"
	// FieldArtistID holds the string denoting the artist_id field in the database.
	FieldArtistID = "artist_id"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// EdgeArtist holds the string denoting the artist edge name in mutations.
	EdgeArtist = "artist"
	// EdgeRelease holds the string denoting the release edge name in mutations.
	EdgeRelease = "release"
	// ArtistFieldID holds the string denoting the ID field of the Artist.
	ArtistFieldID = "id"
	// ReleaseFieldID holds the string denoting the ID field of the Release.
	ReleaseFieldID = "id"
	// Table holds the table name of the releaseappearance in the database.
	Table = "release_appearances"
	// ArtistTable is the table that holds the artist relation/edge.
	ArtistTable = "release_appearances"
	// ArtistInverseTable is the table name for the Artist entity.
	// It exists in this package in order to avoid circular dependency with the "artist" package.
	ArtistInverseTable = "artists"
	// ArtistColumn is the table column denoting the artist relation/edge.
	ArtistColumn = "artist_id"
	// ReleaseTable is the table that holds the release relation/edge.
	ReleaseTable = "release_appearances"
	// ReleaseInverseTable is the table name for the Release entity.
	// It exists in this package in order to avoid circular dependency with the "release" package.
	ReleaseInverseTable = "releases"
	// ReleaseColumn is the table column denoting the release relation/edge.
	ReleaseColumn = "release_id"
)

// Columns holds all SQL columns for releaseappearance fields.
var Columns = []string{
	FieldReleaseID,
	FieldArtistID,
	FieldOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReleaseID holds the default value on creation for the "release_id" field.
	DefaultReleaseID func() pid.ID
	// DefaultArtistID holds the default value on creation for the "artist_id" field.
	DefaultArtistID func() pid.ID
	// OrderValidator is a validator for the "order" field. It is called by the builders before save.
	OrderValidator func(int) error
)

// OrderOption defines the ordering options for the ReleaseAppearance queries.
type OrderOption func(*sql.Selector)

// ByReleaseID orders the results by the release_id field.
func ByReleaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseID, opts...).ToFunc()
}

// ByArtistID orders the results by the artist_id field.
func ByArtistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtistID, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// ByArtistField orders the results by artist field.
func ByArtistField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArtistStep(), sql.OrderByField(field, opts...))
	}
}

// ByReleaseField orders the results by release field.
func ByReleaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReleaseStep(), sql.OrderByField(field, opts...))
	}
}
func newArtistStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, ArtistColumn),
		sqlgraph.To(ArtistInverseTable, ArtistFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ArtistTable, ArtistColumn),
	)
}
func newReleaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, ReleaseColumn),
		sqlgraph.To(ReleaseInverseTable, ReleaseFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ReleaseTable, ReleaseColumn),
	)
}
