// Code generated by ent, DO NOT EDIT.

package releaseappearance

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Pineapple217/cvrs/pkg/ent/predicate"
	"github.com/Pineapple217/cvrs/pkg/pid"
)

// ReleaseID applies equality check predicate on the "release_id" field. It's identical to ReleaseIDEQ.
func ReleaseID(v pid.ID) predicate.ReleaseAppearance {
	vc := int64(v)
	return predicate.ReleaseAppearance(sql.FieldEQ(FieldReleaseID, vc))
}

// ArtistID applies equality check predicate on the "artist_id" field. It's identical to ArtistIDEQ.
func ArtistID(v pid.ID) predicate.ReleaseAppearance {
	vc := int64(v)
	return predicate.ReleaseAppearance(sql.FieldEQ(FieldArtistID, vc))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldEQ(FieldOrder, v))
}

// ReleaseIDEQ applies the EQ predicate on the "release_id" field.
func ReleaseIDEQ(v pid.ID) predicate.ReleaseAppearance {
	vc := int64(v)
	return predicate.ReleaseAppearance(sql.FieldEQ(FieldReleaseID, vc))
}

// ReleaseIDNEQ applies the NEQ predicate on the "release_id" field.
func ReleaseIDNEQ(v pid.ID) predicate.ReleaseAppearance {
	vc := int64(v)
	return predicate.ReleaseAppearance(sql.FieldNEQ(FieldReleaseID, vc))
}

// ReleaseIDIn applies the In predicate on the "release_id" field.
func ReleaseIDIn(vs ...pid.ID) predicate.ReleaseAppearance {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.ReleaseAppearance(sql.FieldIn(FieldReleaseID, v...))
}

// ReleaseIDNotIn applies the NotIn predicate on the "release_id" field.
func ReleaseIDNotIn(vs ...pid.ID) predicate.ReleaseAppearance {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.ReleaseAppearance(sql.FieldNotIn(FieldReleaseID, v...))
}

// ArtistIDEQ applies the EQ predicate on the "artist_id" field.
func ArtistIDEQ(v pid.ID) predicate.ReleaseAppearance {
	vc := int64(v)
	return predicate.ReleaseAppearance(sql.FieldEQ(FieldArtistID, vc))
}

// ArtistIDNEQ applies the NEQ predicate on the "artist_id" field.
func ArtistIDNEQ(v pid.ID) predicate.ReleaseAppearance {
	vc := int64(v)
	return predicate.ReleaseAppearance(sql.FieldNEQ(FieldArtistID, vc))
}

// ArtistIDIn applies the In predicate on the "artist_id" field.
func ArtistIDIn(vs ...pid.ID) predicate.ReleaseAppearance {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.ReleaseAppearance(sql.FieldIn(FieldArtistID, v...))
}

// ArtistIDNotIn applies the NotIn predicate on the "artist_id" field.
func ArtistIDNotIn(vs ...pid.ID) predicate.ReleaseAppearance {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.ReleaseAppearance(sql.FieldNotIn(FieldArtistID, v...))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.FieldLTE(FieldOrder, v))
}

// HasArtist applies the HasEdge predicate on the "artist" edge.
func HasArtist() predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ArtistColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ArtistTable, ArtistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArtistWith applies the HasEdge predicate on the "artist" edge with a given conditions (other predicates).
func HasArtistWith(preds ...predicate.Artist) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(func(s *sql.Selector) {
		step := newArtistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelease applies the HasEdge predicate on the "release" edge.
func HasRelease() predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ReleaseColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ReleaseTable, ReleaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReleaseWith applies the HasEdge predicate on the "release" edge with a given conditions (other predicates).
func HasReleaseWith(preds ...predicate.Release) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(func(s *sql.Selector) {
		step := newReleaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReleaseAppearance) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReleaseAppearance) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReleaseAppearance) predicate.ReleaseAppearance {
	return predicate.ReleaseAppearance(sql.NotPredicates(p))
}
